/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.simple_sql.sQL.SQLPackage#getAndExpression()
 * @model
 * @generated
 */
public interface AndExpression extends Expression
{
} // AndExpression
