/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.simple_sql.sQL.ColumnDefinition#getColumnName <em>Column Name</em>}</li>
 *   <li>{@link org.xtext.example.simple_sql.sQL.ColumnDefinition#getColumnType <em>Column Type</em>}</li>
 *   <li>{@link org.xtext.example.simple_sql.sQL.ColumnDefinition#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.simple_sql.sQL.SQLPackage#getColumnDefinition()
 * @model
 * @generated
 */
public interface ColumnDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Column Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Name</em>' attribute.
   * @see #setColumnName(String)
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getColumnDefinition_ColumnName()
   * @model
   * @generated
   */
  String getColumnName();

  /**
   * Sets the value of the '{@link org.xtext.example.simple_sql.sQL.ColumnDefinition#getColumnName <em>Column Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Name</em>' attribute.
   * @see #getColumnName()
   * @generated
   */
  void setColumnName(String value);

  /**
   * Returns the value of the '<em><b>Column Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Type</em>' containment reference.
   * @see #setColumnType(ColumnType)
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getColumnDefinition_ColumnType()
   * @model containment="true"
   * @generated
   */
  ColumnType getColumnType();

  /**
   * Sets the value of the '{@link org.xtext.example.simple_sql.sQL.ColumnDefinition#getColumnType <em>Column Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Type</em>' containment reference.
   * @see #getColumnType()
   * @generated
   */
  void setColumnType(ColumnType value);

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' attribute list.
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getColumnDefinition_Constraints()
   * @model unique="false"
   * @generated
   */
  EList<String> getConstraints();

} // ColumnDefinition
