/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Table Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.simple_sql.sQL.CreateTableStatement#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.simple_sql.sQL.SQLPackage#getCreateTableStatement()
 * @model
 * @generated
 */
public interface CreateTableStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.simple_sql.sQL.ColumnDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getCreateTableStatement_Columns()
   * @model containment="true"
   * @generated
   */
  EList<ColumnDefinition> getColumns();

} // CreateTableStatement
