/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selected Columns</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.simple_sql.sQL.SelectedColumns#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.simple_sql.sQL.SQLPackage#getSelectedColumns()
 * @model
 * @generated
 */
public interface SelectedColumns extends EObject
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' attribute list.
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getSelectedColumns_Columns()
   * @model unique="false"
   * @generated
   */
  EList<String> getColumns();

} // SelectedColumns
