/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.simple_sql.sQL.SelectStatement#getSelectedColumns <em>Selected Columns</em>}</li>
 *   <li>{@link org.xtext.example.simple_sql.sQL.SelectStatement#getWhereClause <em>Where Clause</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.simple_sql.sQL.SQLPackage#getSelectStatement()
 * @model
 * @generated
 */
public interface SelectStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Selected Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected Columns</em>' containment reference.
   * @see #setSelectedColumns(SelectedColumns)
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getSelectStatement_SelectedColumns()
   * @model containment="true"
   * @generated
   */
  SelectedColumns getSelectedColumns();

  /**
   * Sets the value of the '{@link org.xtext.example.simple_sql.sQL.SelectStatement#getSelectedColumns <em>Selected Columns</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected Columns</em>' containment reference.
   * @see #getSelectedColumns()
   * @generated
   */
  void setSelectedColumns(SelectedColumns value);

  /**
   * Returns the value of the '<em><b>Where Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where Clause</em>' containment reference.
   * @see #setWhereClause(WhereClause)
   * @see org.xtext.example.simple_sql.sQL.SQLPackage#getSelectStatement_WhereClause()
   * @model containment="true"
   * @generated
   */
  WhereClause getWhereClause();

  /**
   * Sets the value of the '{@link org.xtext.example.simple_sql.sQL.SelectStatement#getWhereClause <em>Where Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where Clause</em>' containment reference.
   * @see #getWhereClause()
   * @generated
   */
  void setWhereClause(WhereClause value);

} // SelectStatement
