/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.simple_sql.sQL.SQLPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
} // Value
