/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SQLUiModule extends AbstractSQLUiModule {

	public SQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
