/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSQLScopeProvider extends DelegatingScopeProvider {
}
