/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.sQL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.simple_sql.sQL.OrExpression;
import org.xtext.example.simple_sql.sQL.SQLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Or Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OrExpressionImpl extends ExpressionImpl implements OrExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OrExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SQLPackage.Literals.OR_EXPRESSION;
  }

} //OrExpressionImpl
