/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.simple_sql.ui.internal.Simple_sqlActivator;

public class SQLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Simple_sqlActivator.getInstance().getInjector("org.xtext.example.simple_sql.SQL");
	}

}
