/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SQLRuntimeModule extends AbstractSQLRuntimeModule {
}
