/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.simple_sql.services.SQLGrammarAccess;

@SuppressWarnings("all")
public class SQLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SQLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ColumnDefinition_CommaKeyword_3_q;
	protected AbstractElementAlias match_ColumnType_BOOLEANKeyword_2_1_or_INTKeyword_0_1_or_TINYINTKeyword_3_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SQLGrammarAccess) access;
		match_ColumnDefinition_CommaKeyword_3_q = new TokenAlias(false, true, grammarAccess.getColumnDefinitionAccess().getCommaKeyword_3());
		match_ColumnType_BOOLEANKeyword_2_1_or_INTKeyword_0_1_or_TINYINTKeyword_3_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getColumnTypeAccess().getBOOLEANKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getColumnTypeAccess().getINTKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getColumnTypeAccess().getTINYINTKeyword_3_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ColumnDefinition_CommaKeyword_3_q.equals(syntax))
				emit_ColumnDefinition_CommaKeyword_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ColumnType_BOOLEANKeyword_2_1_or_INTKeyword_0_1_or_TINYINTKeyword_3_1.equals(syntax))
				emit_ColumnType_BOOLEANKeyword_2_1_or_INTKeyword_0_1_or_TINYINTKeyword_3_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     columnType=ColumnType (ambiguity) (rule end)
	 *     constraints+=Constraint (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_ColumnDefinition_CommaKeyword_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'INT' | 'BOOLEAN' | 'TINYINT'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_ColumnType_BOOLEANKeyword_2_1_or_INTKeyword_0_1_or_TINYINTKeyword_3_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
