/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.simple_sql.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.simple_sql.ui.internal.Simple_sqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Simple_sqlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Simple_sqlActivator activator = Simple_sqlActivator.getInstance();
		return activator != null ? activator.getInjector(Simple_sqlActivator.ORG_XTEXT_EXAMPLE_SIMPLE_SQL_SQL) : null;
	}

}
